---
- name: Add official Debian repository
  package:
    name: firefox-esr-l10n-en-ca
    state: present
  become: yes

- name: create policy directory
  become: true
  file:
    path: '/etc/firefox/policies'
    state: directory

- name: Updating Firefox Policies
  become: true
  vars:
    FirfoxPlugins:
      - "foxyproxy-standard"
      - "darkreader"
      - "bitwarden-password-manager"
      - "ublock-origin"
      - "wappalyzer"
      - "multi-account"
      - "grammarly-1"
      - "simplelogin"
      - "simplify-jobs"
  template:
    src: '{{ playbook_dir }}/templates/policies.json.j2'
    dest: '/etc/firefox/policies/policies.json'
    mode: '0644'
    owner: root
    group: root


