- name: Install flatpak
  become: true
  package:
    name:
      - flatpak
  tags:
    - flatpak
    - install

- name: Add flathub repo
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
    - install

- name: Install flatpak GUI extras
  shell: "flatpak install -y {{ item }}"
  loop:
    - com.github.tchx84.Flatseal
    - flathub us.zoom.Zoom
    - com.visualstudio.code
  tags:
    - flatpak
    - install
    - gui-extras
