---
- name: Create .fonts symlink
  file:
    src: "{{ playbook_dir }}/../.fonts"
    dest: "~/.fonts" 
    force: true
    state: link
  tags:
    - fonts

- name: Rebuild font cache
  shell: "fc-cache -fv"
  tags:
    - fonts
